import {esc} from './model.js';
import {sanitize} from './sanitize.js';

const safeColor=c=>['green','red','orange','inherit','#DE47A3','#B75DCC'].includes(c)?c:'inherit';
const secDomId=s=>`section-${s.id}`;
const stripHtml=s=>String(s||'').replace(/<[^>]+>/g,' ');

function renderHeader(project,assets){return `<header class="tfr-site-header">
 <button class="tfr-hamburger" data-toc-toggle aria-label="Contents">☰</button>
 <div class="tfr-brand"><img src="${assets.logo}" alt=""><span>The Fire Rises Wiki</span></div>
 <div class="tfr-search-wrap"><div class="tfr-search-row"><input class="tfr-search" placeholder="Search The Fire Rises Wiki"><button class="tfr-search-button">Search</button></div><div class="tfr-search-results"></div></div>
 <div class="tfr-account"><span>⚑ English</span><span class="fake">Create account</span><span class="fake">Log in</span><span>•••</span></div>
 </header>`}

function renderToc(page){return `<ul class="tfr-toc-list"><li><a href="#article-top" data-scroll="article-top">Beginning</a></li>${page.sections.map(s=>`<li class="${s.level===3?'sub':''}"><a href="#${secDomId(s)}" data-scroll="${secDomId(s)}">${esc(s.title)}</a></li>`).join('')}</ul>`}
function renderAppearance(){return `<div class="tfr-side-inner"><div class="tfr-side-heading"><strong>Appearance</strong><button data-appearance-hide>hide</button></div><div class="tfr-appearance-section"><span>Text</span><label><input type="radio" name="text-size" value="small"> Small</label><label><input type="radio" name="text-size" value="standard" checked> Standard</label><label><input type="radio" name="text-size" value="large"> Large</label></div><div class="tfr-appearance-section"><span>Width</span><label><input type="radio" name="page-width" value="standard" checked> Standard</label><label><input type="radio" name="page-width" value="wide"> Wide</label></div></div>`}

function renderInfoboxMediaTabs(page){const tabs=page.infobox.tabs||[];if(!tabs.length)return'';const active=tabs.some(t=>t.id===page.infobox.activeTabId)?page.infobox.activeTabId:tabs[0].id;return `<tr><td colspan="2"><div class="tfr-media-tabs">${tabs.length>1?tabs.map(t=>`<button type="button" class="tfr-media-tab ${t.id===active?'active':''}" data-media-tab="${esc(t.id)}" aria-pressed="${t.id===active?'true':'false'}">${esc(t.label)}</button>`).join(''):''}</div>${tabs.map(t=>`<div class="tfr-media-panel" data-media-panel="${esc(t.id)}" ${t.id===active?'':'hidden'}>${t.src?`<img src="${t.src}" alt="" style="width:${Math.max(40,Number(t.width)||156)}px">`:''}${t.caption?`<div class="tfr-caption">${esc(t.caption)}</div>`:''}</div>`).join('')}</td></tr>`}
function rowLabel(r){return `${r.type!=='trait'&&r.icon?`<img class="tfr-row-icon" src="${r.icon}" alt="">`:''}<span>${esc(r.label)}</span>`}
function renderListItems(r){return `<ul class="tfr-ib-list">${(r.items||[]).map(i=>`<li>${i.icon?`<img class="tfr-ib-icon" src="${i.icon}" alt="">`:''}<span>${sanitize(i.text||'')}</span></li>`).join('')}</ul>`}
function renderTraitItems(r){return `<div class="tfr-trait-list">${(r.items||[]).map(i=>`<div class="tfr-trait-entry"><div class="tfr-trait-title">${esc(String(i.text||'').replace(/<[^>]*>/g,''))}</div><ul class="tfr-trait-bonus-list">${(i.bonuses||[]).filter(b=>b.icon||b.text||b.stat).map(b=>`<li>${b.icon?`<img class="tfr-ib-icon tfr-trait-bonus-icon" src="${b.icon}" alt="">`:''}${b.text?`<span class="tfr-trait-bonus-text">${esc(b.text)}</span>`:''}${b.stat?`${b.text?' ':''}<strong class="tfr-trait-bonus-value" style="color:${safeColor(b.statColor)}">${esc(b.stat)}</strong>`:''}</li>`).join('')}</ul></div>`).join('')}</div>`}
function renderInfobox(page){const groups=page.infobox.groups.map(g=>`<tr><th colspan="2" class="group-title">${esc(g.title)}</th></tr>${g.rows.map(r=>{const content=r.type==='list'?renderListItems(r):r.type==='trait'?renderTraitItems(r):`<span class="tfr-text-value" style="color:${safeColor(r.valueColor)}">${sanitize(r.value||'')}</span>`;return `<tr><th>${rowLabel(r)}</th><td>${content}</td></tr>`}).join('')}`).join('');const sec=page.infobox.secondary;return `<table class="tfr-infobox"><tbody><tr><th colspan="2" class="title">${esc(page.infobox.title||page.title)}</th></tr>${renderInfoboxMediaTabs(page)}${sec?.src?`<tr><td colspan="2" class="tfr-secondary"><img src="${sec.src}" alt="" style="width:${Math.max(40,Number(sec.width)||420)}px">${sec.caption?`<div class="tfr-caption">${esc(sec.caption)}</div>`:''}</td></tr>`:''}${groups}</tbody></table>`}

function routeFlag(flag,assets){if(!flag)return'';return `<span class="tfr-route-flag"><img class="tfr-route-flag-image" src="${flag}" alt=""><img class="tfr-route-flag-frame" src="${assets.flagFrame||''}" alt=""></span>`}
function routeLink(entry,assets){if(!entry?.title&&!entry?.flag)return'';const body=`${routeFlag(entry.flag,assets)}<span>${esc(entry.title||'Untitled path')}</span>`;return entry.pageId?`<a class="tfr-route-link" href="#page=${encodeURIComponent(entry.pageId)}" data-page-link="${esc(entry.pageId)}">${body}</a>`:`<span class="tfr-route-link">${body}</span>`}
function renderCountryPaths(page,assets){const c=page.countryPaths;if(page.type!=='country'||!c?.enabled)return'';const hasRoot=c.root?.title||c.root?.flag;const paths=(c.paths||[]).filter(x=>x.title||x.flag);if(!hasRoot&&!paths.length&&!c.quote)return'';return `<div class="tfr-country-routes">${hasRoot?`<div class="tfr-route-root">${routeLink(c.root,assets)}</div>`:''}${c.quote?`<div class="tfr-route-quote"><em>“${esc(c.quote)}”</em></div>`:''}${paths.length?`<div class="tfr-route-paths">${paths.map(x=>`<div class="tfr-route-path">${routeLink(x,assets)}</div>`).join('')}</div>`:''}</div>`}
function renderLead(page){const m=page.leadImage;if(!m?.src)return'';const quote=m.quote?`<div class="tfr-lead-quote">${esc(m.quote).replace(/\r?\n/g,'<br>')}</div>`:'';return `<figure class="tfr-lead"><img src="${m.src}" alt="" style="width:${Math.max(40,Number(m.width)||350)}px">${m.caption?`<figcaption class="tfr-caption">${esc(m.caption)}</figcaption>`:''}${quote}</figure>`}
function renderSection(page,s,showEditLinks){const medias=(s.media||[]).map(m=>m.src?`<figure class="tfr-section-media" style="width:${Math.max(80,Number(m.width)||260)}px"><img src="${m.src}" alt="">${m.caption?`<figcaption>${esc(m.caption)}</figcaption>`:''}</figure>`:'').join('');const headTag=s.level===3?'h3':'h2';const edit=showEditLinks?`<span class="tfr-edit-links">[ <a href="#" data-edit-section="${esc(s.id)}">edit</a> | <a href="#" data-edit-section="${esc(s.id)}">edit source</a> ]</span>`:'';if(s.type==='gallery'){return `<section id="${secDomId(s)}"><div class="tfr-heading"><${headTag}>${esc(s.title)}</${headTag}>${edit}</div><div class="tfr-gallery">${(s.gallery||[]).map(g=>`<figure><div class="tfr-gallery-image">${g.src?`<img src="${g.src}" alt="">`:''}</div><figcaption>${esc(g.caption||'')}</figcaption></figure>`).join('')}</div></section>`}return `<section id="${secDomId(s)}"><div class="tfr-heading"><${headTag}>${esc(s.title)}</${headTag}>${edit}</div>${medias}<div class="tfr-section-body">${sanitize(s.html)}</div></section>`}
function renderBody(project,page,assets){return `${renderCountryPaths(page,assets)}${renderInfobox(page)}${renderLead(page)}<div class="tfr-intro">${sanitize(page.introHtml)}</div>${page.sections.map(s=>renderSection(page,s,project.settings.showEditLinks)).join('')}${page.categories.length?`<div class="tfr-catlinks">Categories: ${page.categories.map(c=>`<a href="#">${esc(c)}</a>`).join(' | ')}</div>`:''}`}

export function pageMarkup(project,page,assets){return `<div class="tfr-reader text-standard width-standard" data-page-root="${esc(page.id)}">${renderHeader(project,assets)}<div class="tfr-layout"><aside class="tfr-side tfr-toc"><div class="tfr-side-inner"><div class="tfr-side-heading"><strong>Contents</strong><button data-toc-hide>hide</button></div>${renderToc(page)}</div></aside><main class="tfr-main" id="article-top"><div class="tfr-title-row"><div class="tfr-toc-inline-wrap"><button class="tfr-toc-inline" data-toc-menu-toggle aria-label="Contents" aria-expanded="false">☷</button><div class="tfr-toc-popover" hidden>${renderToc(page)}</div></div><h1>${esc(page.title)}</h1><button class="tfr-mobile-search-toggle" type="button" data-mobile-search-toggle aria-label="Search pages" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" fill="none" stroke="currentColor" stroke-width="2"/><path d="M15.5 15.5 21 21" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square"/></svg></button><div class="tfr-search-wrap tfr-mobile-search-wrap" hidden><div class="tfr-search-row"><input class="tfr-search" type="search" autocomplete="off" placeholder="Search this lore..." aria-label="Search pages"><button class="tfr-mobile-search-close" type="button" data-mobile-search-close aria-label="Close search">×</button></div><div class="tfr-search-results"></div></div></div><div class="tfr-tabs"><div class="tfr-tab-group"><a class="tfr-tab active" href="#">Page</a><a class="tfr-tab discussion" href="#" data-edit-page>Discussion</a></div><div class="tfr-tab-group right"><a class="tfr-tab active desktop-only" href="#">Read</a><a class="tfr-tab desktop-only" href="#" data-edit-page>Edit</a><a class="tfr-tab desktop-only" href="#" data-edit-page>Edit source</a><a class="tfr-tab desktop-only" href="#">View history</a><details class="tfr-tools"><summary>Tools</summary><div class="tfr-tools-menu"><button data-tool="toc">Contents</button><button data-tool="appearance">Appearance</button><button data-tool="sound">Sound: on</button></div></details></div></div><article class="tfr-article">${renderBody(project,page,assets)}</article></main><aside class="tfr-side tfr-appearance">${renderAppearance()}</aside></div></div>`}

function runtime(project,mode,sounds){
  const runtimeProject={pages:project.pages.map(p=>({id:p.id,title:p.title,introHtml:p.introHtml||'',sections:(p.sections||[]).map(s=>({title:s.title||'',html:s.html||''}))}))};
  const data=JSON.stringify(runtimeProject).replace(/</g,'\\u003c');
  const snd=JSON.stringify(sounds).replace(/</g,'\\u003c');
  return `<script>(function(){
const PROJECT=${data},MODE=${JSON.stringify(mode)},SOUNDS=${snd};
const PHONE=window.matchMedia?.('(max-width:760px)').matches||false;
let muted=PHONE;
const pools={};
for(const [k,src] of Object.entries(SOUNDS)){pools[k]=Array.from({length:4},()=>{const a=new Audio(src);a.volume=.7;return a})}
function play(n){if(muted||!pools[n])return;const a=pools[n].find(x=>x.paused||x.ended)||pools[n][0];try{a.currentTime=0;a.play().catch(()=>{})}catch{}}
function strip(s){return String(s||'').replace(/<[^>]+>/g,' ')}
function soundFor(t){if(t.closest('input,textarea,[contenteditable=true]'))return'province';if(t.closest('[data-toc-hide],[data-appearance-hide]'))return'close';if(t.closest('button,a,summary,select,label'))return'open';return null}
document.addEventListener('pointerdown',e=>{const s=soundFor(e.target);if(s)play(s)},true);
function activateMediaTab(mt){const box=mt?.closest?.('.tfr-infobox');if(!box)return false;const id=mt.dataset.mediaTab;box.querySelectorAll('[data-media-tab]').forEach(x=>{const active=x.dataset.mediaTab===id;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active?'true':'false')});box.querySelectorAll('[data-media-panel]').forEach(x=>{x.hidden=x.dataset.mediaPanel!==id});return true}
function mediaTabFromEvent(e){const target=e.target instanceof Element?e.target:null;const mt=target?.closest?.('[data-media-tab]');return mt?activateMediaTab(mt):false}
document.addEventListener('pointerup',e=>{if(e.pointerType==='touch'&&mediaTabFromEvent(e))e.preventDefault()},true);
if(!window.PointerEvent)document.addEventListener('touchend',e=>{if(mediaTabFromEvent(e))e.preventDefault()},{capture:true,passive:false});
function activeRoot(){return document.querySelector('.export-page:not([hidden]) .tfr-reader')||document.querySelector('.tfr-reader')}
function showPage(id){if(MODE!=='export'){parent.postMessage({type:'navigate-page',id},'*');return}document.querySelectorAll('.export-page').forEach(x=>{x.hidden=x.dataset.page!==id});history.replaceState(null,'','#page='+encodeURIComponent(id));scrollTo(0,0)}
function search(input){const q=input.value.trim().toLowerCase(),box=input.closest('.tfr-search-wrap').querySelector('.tfr-search-results');if(!q){box.innerHTML='';return}const arr=PROJECT.pages.map(p=>{const hay=(p.title+' '+strip(p.introHtml)+' '+p.sections.map(s=>s.title+' '+strip(s.html)).join(' ')).toLowerCase();const title=p.title.toLowerCase();return{p,score:title.startsWith(q)?0:title.includes(q)?1:hay.includes(q)?2:99}}).filter(x=>x.score<99).sort((a,b)=>a.score-b.score||a.p.title.localeCompare(b.p.title)).slice(0,8);box.innerHTML=arr.map(x=>'<button class="tfr-search-result" data-result="'+x.p.id+'"><strong>'+x.p.title+'</strong><small>'+(x.score===2?'Content match':'Page')+'</small></button>').join('')}
document.addEventListener('input',e=>{if(e.target.matches('.tfr-search'))search(e.target)});
document.addEventListener('click',e=>{
 const mobileSearchToggle=e.target.closest('[data-mobile-search-toggle]');if(mobileSearchToggle){const row=mobileSearchToggle.closest('.tfr-title-row'),wrap=row?.querySelector('.tfr-mobile-search-wrap');if(row&&wrap){row.classList.add('mobile-search-open');wrap.hidden=false;mobileSearchToggle.setAttribute('aria-expanded','true');requestAnimationFrame(()=>wrap.querySelector('.tfr-search')?.focus())}return}
 const mobileSearchClose=e.target.closest('[data-mobile-search-close]');if(mobileSearchClose){const row=mobileSearchClose.closest('.tfr-title-row'),wrap=row?.querySelector('.tfr-mobile-search-wrap'),input=wrap?.querySelector('.tfr-search');if(input){input.value='';search(input)}if(wrap)wrap.hidden=true;row?.classList.remove('mobile-search-open');row?.querySelector('[data-mobile-search-toggle]')?.setAttribute('aria-expanded','false');return}
 const r=e.target.closest('[data-result]');if(r){showPage(r.dataset.result);return}
 const pl=e.target.closest('[data-page-link]');if(pl){e.preventDefault();showPage(pl.dataset.pageLink);return}
 const mt=e.target.closest('[data-media-tab]');if(mt){e.preventDefault();activateMediaTab(mt);return}
 const ed=e.target.closest('[data-edit-section]');if(ed){e.preventDefault();if(MODE==='preview')parent.postMessage({type:'edit-section',id:ed.dataset.editSection},'*');return}
 if(e.target.closest('[data-edit-page]')){e.preventDefault();if(MODE==='preview')parent.postMessage({type:'edit-page'},'*');return}
 const root=e.target.closest('.tfr-reader')||activeRoot();if(!root)return;
 if(e.target.closest('[data-toc-hide]')){root.querySelector('.tfr-layout').classList.add('toc-collapsed');return}
 if(e.target.closest('[data-toc-toggle]')){root.querySelector('.tfr-layout').classList.toggle('toc-collapsed');return}
 if(e.target.closest('[data-appearance-hide]')){root.querySelector('.tfr-layout').classList.add('appearance-collapsed');return}
 const tool=e.target.closest('[data-tool]');if(tool){const layout=root.querySelector('.tfr-layout');if(tool.dataset.tool==='toc')layout.classList.toggle('toc-collapsed');if(tool.dataset.tool==='appearance')layout.classList.toggle('appearance-collapsed');if(tool.dataset.tool==='sound'){muted=!muted;tool.textContent='Sound: '+(muted?'off':'on');if(!muted)play('open')}return}
 const sc=e.target.closest('[data-scroll]');if(sc){e.preventDefault();root.querySelector('#'+CSS.escape(sc.dataset.scroll))?.scrollIntoView({behavior:'smooth'});return}
});
document.addEventListener('change',e=>{const root=e.target.closest('.tfr-reader')||activeRoot();if(!root)return;if(e.target.name==='text-size'){root.classList.remove('text-small','text-standard','text-large');root.classList.add('text-'+e.target.value)}if(e.target.name==='page-width'){root.classList.remove('width-standard','width-wide');root.classList.add('width-'+e.target.value)}});
document.querySelectorAll('[data-tool="sound"]').forEach(x=>x.textContent='Sound: '+(muted?'off':'on'));
if(MODE==='preview'){let heightQueued=false,lastHeight=0;const previewRoot=document.querySelector('.tfr-reader');const reportHeight=()=>{heightQueued=false;const target=previewRoot||document.body;if(!target)return;const box=target.getBoundingClientRect();const h=Math.ceil(Math.max(target.scrollHeight||0,target.offsetHeight||0,box.height||0));if(h>0&&Math.abs(h-lastHeight)>1){lastHeight=h;parent.postMessage({type:'preview-height',height:h},'*')}};const queueHeight=()=>{if(heightQueued)return;heightQueued=true;requestAnimationFrame(reportHeight)};addEventListener('load',queueHeight,{once:true});addEventListener('resize',queueHeight);if(window.ResizeObserver&&previewRoot)new ResizeObserver(queueHeight).observe(previewRoot);document.fonts?.ready?.then(queueHeight).catch(()=>{});document.querySelectorAll('img').forEach(img=>{if(!img.complete)img.addEventListener('load',queueHeight,{once:true})});queueHeight()}
if(MODE==='export'){const id=new URLSearchParams(location.hash.slice(1)).get('page');if(id&&PROJECT.pages.some(p=>p.id===id))showPage(id)}
})();<\/script>`
}

export function previewDocument(project,page,themeCss,assets,sounds){const cursor=`url('${assets.cursor}'), pointer`;const pointer=`url('${assets.pointer}'), pointer`;return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Electrolize&display=swap" rel="stylesheet"><link href="https://fonts.cdnfonts.com/css/vcr-osd-mono" rel="stylesheet"><style>${themeCss}</style><style>:root{--cursor-normal:${cursor};--cursor-pointer:${pointer}}</style></head><body class="tfr-page">${pageMarkup(project,page,assets)}${runtime(project,'preview',sounds)}</body></html>`}
export function exportDocument(project,themeCss,assets,sounds){const pages=project.pages.map(p=>`<section class="export-page" data-page="${esc(p.id)}" ${p.id===project.activePageId?'':'hidden'}>${pageMarkup(project,p,assets)}</section>`).join('');const data=JSON.stringify(project).replace(/</g,'\\u003c');return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>The Fire Rises Wiki</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Electrolize&display=swap" rel="stylesheet"><link href="https://fonts.cdnfonts.com/css/vcr-osd-mono" rel="stylesheet"><style>${themeCss}</style><style>:root{--cursor-normal:url('${assets.cursor}'),pointer;--cursor-pointer:url('${assets.pointer}'),pointer}.export-page[hidden]{display:none!important}</style></head><body class="tfr-page">${pages}<script id="lore-project-data" type="application/json">${data}</script>${runtime(project,'export',sounds)}</body></html>`}
